name: Maven CI with Cucumber

# Déclenche le workflow sur chaque push
on:
  push:
    branches:
      - main 

# Définition des jobs
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Java (JDK)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Version de Java utilisée
          distribution: 'temurin' # Distribution de JDK

      # Étape 3 : Installation des dépendances Maven
      - name: Install dependencies
        run: mvn clean install

      # Étape 4 : Exécution des tests Cucumber
      - name: Run Cucumber tests  
        run: mvn test verify

      # Étape 5 : Archivage des rapports Cucumber
      # Upload des rapports dans différents formats pour s'assurer de capturer tous les résultats
      - name: Archive Cucumber reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: |
            target/jsonReports/
            target/cucumber-reports/
            target/surefire-reports/
            
      # Étape 6 : Téléchargement des rapports pour vérification
      # Cette étape permet de vérifier que les artifacts sont correctement créés
      - name: Download Cucumber reports
        uses: actions/download-artifact@v4
        with:
          name: cucumber-reports
          path: downloaded-reports
          
      # Étape 7 : Affichage du contenu des rapports téléchargés
      # Cette étape permet de vérifier dans les logs quels fichiers ont été générés
      - name: List downloaded files
        run: ls -R downloaded-reports
